### ISSUE TITLE
Animals Still Grow Despite Being Named

### ISSUE THREAD

**Issue by Llohgun** [WheelerShigley/Minecraft-Mods#3]
Minecraft Version: 1.21.1
Mod Version: 1.2.1
Fabric: 0.16.14

Hi! As the title states, animals still grow despite being named with a name tag. On top of that, the unnaming function doesn't seem to work either. I tested with no other mods enabled, and used "/tick sprint 1200" on a new world with cows and pigs (feeding also worked).

Anything else I can add? Out of what I've found, I like this mods method of keeping baby animals the most, so I'm hoping to get it fixed!

**Comment by NeverEndingCycle** [comment]
Can confirm, this is also not working in 1.21.5.

**Comment by WheelerShigley** [comment]
This is catastrophic!
I will fix this immediately.

**Comment by WheelerShigley** [comment]
This should fix it for both problems.
https://modrinth.com/mod/lil-guy/version/1.2.3_1.20.5-1.21.5

What happened was: I was accounting for client-side changes (for some reason) and must have done it wrong.
The mod is server-side only, so I'm unsure why I had decided to try to do that.

I will now check if versions under 1.20.5 also have this problem.

**Comment by Llohgun** [comment]
After another quick test, the issue still seems to be happening post patch.
